name: "Crowdsec Cloudflare Bouncer - Custom"
description: "Crowdsec Cloudflare bouncer"
url: "https://github.com/samsedge/home-assistant-addons/edit/main/crowdsec-cloudflare-bouncer/DOCS.md"
codenotary: k@bogaerts.org
version: "v0.0.3"
slug: crowdsec-cloudflare-bouncer
init: false
auth_api: true
arch:
  - x64

image: "ghcr.io/krisbogaerts/{arch}-addon-crowdsec-cloudflare-bouncer"
options:
  api_url: "http://424ccef4-crowdsec:8080/"
  api_key: ""
  update_frequency: "10s"
  log_level: info
  cloudflare_id: ""
  cloudflare_token: ""
  cloudflare_zone_id: ""
schema:
  api_url: str
  api_key: str
  update_frequency: str
  log_level: list(info|error|debug)
  cloudflare_id: str
  cloudflare_token: str
  cloudflare_zone_id: str
map:
  - config:rw
